"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Layers, MoreHorizontal, Trash2 } from "lucide-react";
import { api } from "@/lib/api";
import {
  specializationsApi,
  type SpecializationGrade,
  type SpecializationListItem,
} from "@/lib/api/specializations";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { ConfirmDialog } from "@/components/confirm-dialog";
import { CompanyTabs } from "@/components/company/company-tabs";
import { usePermissions } from "@/hooks/use-permissions";
import { AddGradesModal } from "@/components/specialization/add-grades-modal";
import { UsageReferencesList } from "@/components/specialization/usage-references-list";
import {
  dictionariesApi,
  type DictionaryItemUsage,
} from "@/lib/api/dictionaries";
import { ActiveAiSessionBadge } from "@/components/competence-generation/ActiveAiSessionBadge";
import { useActiveAiSessions } from "@/hooks/use-active-ai-sessions";
import { findMatrixSessionForSpec } from "@/lib/active-ai-session-match";
import { activeSessionRoute } from "@/lib/active-ai-session-route";

export default function SpecializationsPage() {
  const [items, setItems] = useState<SpecializationListItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [deleting, setDeleting] = useState<SpecializationListItem | null>(null);
  const [deleteBusy, setDeleteBusy] = useState(false);
  // HRP-103 redo: prefetch references while the confirm is open so the
  // operator sees the exact positions / grade chains to detach.
  // `null` = loading, `undefined` = not yet requested or no references.
  const [deleteUsage, setDeleteUsage] = useState<DictionaryItemUsage | null>(
    null,
  );
  // HRP-158: per-row "Manage grades" entry in the kebab menu opens the
  // same modal the detail page uses. `gradeMeta` is fetched lazily so the
  // list view never pays the round-trip until the operator actually opens
  // the dialog.
  const [managingGrades, setManagingGrades] =
    useState<SpecializationListItem | null>(null);
  const [managingGradesMeta, setManagingGradesMeta] = useState<
    SpecializationGrade[] | null
  >(null);
  const { canManage } = usePermissions();
  const router = useRouter();
  // HRP-33 REDO: highlight rows whose matrix is being generated by an
  // active AI session, so the operator can spot in-flight work from the
  // list view and one-click jump back to the live drawer.
  const { all: activeAiSessions } = useActiveAiSessions();

  const load = useCallback(async () => {
    try {
      const data = await specializationsApi.list();
      setItems(data);
    } catch (err) {
      toast.error(
        err instanceof Error ? err.message : "Failed to load specializations",
      );
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const data = await specializationsApi.list();
        if (!cancelled) setItems(data);
      } catch (err) {
        toast.error(
          err instanceof Error ? err.message : "Failed to load specializations",
        );
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  async function confirmDelete() {
    if (!deleting) return;
    setDeleteBusy(true);
    try {
      await api.delete(`/dictionaries/items/${deleting.id}`);
      toast.success(`"${deleting.title}" deleted`);
      setDeleting(null);
      setDeleteUsage(null);
      await load();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to delete");
    } finally {
      setDeleteBusy(false);
    }
  }

  // HRP-103 redo: refresh the usage preview every time a different
  // specialization opens the confirm. Cancellation guards against stale
  // results when the operator clicks Delete on two rows in quick
  // succession.
  useEffect(() => {
    if (!deleting) {
      setDeleteUsage(null);
      return;
    }
    let cancelled = false;
    setDeleteUsage(null);
    (async () => {
      try {
        const usage = await dictionariesApi.usage(deleting.id);
        if (!cancelled) setDeleteUsage(usage);
      } catch {
        // A failed preview shouldn't block the operator from attempting
        // delete — the 409 path still surfaces a usable error toast.
        if (!cancelled)
          setDeleteUsage({
            positions: [],
            chains: [],
            assessments_count: 0,
            assessment_groups_count: 0,
            pdps_count: 0,
            exam_pass_marks_count: 0,
            competences_count: 0,
          });
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [deleting]);

  const deleteHasReferences =
    deleteUsage !== null &&
    (deleteUsage.positions.length > 0 ||
      deleteUsage.chains.length > 0 ||
      deleteUsage.assessments_count > 0 ||
      deleteUsage.assessment_groups_count > 0 ||
      deleteUsage.pdps_count > 0 ||
      deleteUsage.exam_pass_marks_count > 0);

  async function openManageGrades(spec: SpecializationListItem) {
    setManagingGrades(spec);
    setManagingGradesMeta(null);
    try {
      const grades = await specializationsApi.grades(spec.id);
      setManagingGradesMeta(grades);
    } catch (err) {
      toast.error(
        err instanceof Error ? err.message : "Failed to load grades",
      );
      setManagingGrades(null);
    }
  }

  function closeManageGrades() {
    setManagingGrades(null);
    setManagingGradesMeta(null);
  }

  const filtered = search
    ? items.filter((i) =>
        i.title.toLowerCase().includes(search.toLowerCase()),
      )
    : items;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">Company</h1>
        <p className="text-sm text-muted-foreground">Organization structure</p>
      </div>

      <CompanyTabs />

      <div className="flex items-center justify-between">
        <Input
          data-testid="specializations-search"
          placeholder="Search specializations..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="max-w-xs"
        />
        <p className="text-xs text-muted-foreground">
          Add or rename entries in Settings → Dictionaries → Specializations
        </p>
      </div>

      {loading ? (
        <div className="py-12 text-center text-sm text-muted-foreground">
          Loading...
        </div>
      ) : (
        <Table data-testid="specializations-table">
          <TableHeader>
            <TableRow>
              <TableHead>Specialization</TableHead>
              <TableHead className="w-24 text-right">Grades</TableHead>
              <TableHead className="w-28 text-right">Positions</TableHead>
              <TableHead className="w-32 text-right">Assigned / plan</TableHead>
              {canManage && <TableHead className="w-12" />}
            </TableRow>
          </TableHeader>
          <TableBody>
            {filtered.map((spec) => {
              const activeSession = findMatrixSessionForSpec(
                activeAiSessions,
                spec.id,
              );
              return (
              <TableRow
                key={spec.id}
                data-testid={`specializations-row-${spec.id}`}
                className={activeSession ? "bg-primary/5" : undefined}
              >
                <TableCell className="font-medium">
                  <div className="flex items-center gap-2">
                    <Link
                      href={`/company/specializations/${spec.id}`}
                      className="hover:underline"
                    >
                      {spec.title}
                    </Link>
                    {activeSession ? (
                      <ActiveAiSessionBadge
                        sessions={[activeSession]}
                        onOpen={() =>
                          router.push(
                            activeSessionRoute({
                              id: activeSession.session_id,
                              scope: activeSession.scope,
                              target_id: activeSession.target_id,
                              status: activeSession.status,
                              // HRP-33 review fix: carry the originating
                              // position id when the session has one so
                              // Apply lands back on the position page.
                              params: {
                                position_id: activeSession.position_id,
                              },
                            }),
                          )
                        }
                        testIdSuffix={`specializations-row-${spec.id}`}
                      />
                    ) : null}
                  </div>
                </TableCell>
                <TableCell className="text-right">{spec.grade_count}</TableCell>
                <TableCell className="text-right">
                  {spec.position_count}
                </TableCell>
                <TableCell className="text-right">
                  {spec.assigned_count}/{spec.headcount_total}
                </TableCell>
                {canManage && (
                  <TableCell>
                    <DropdownMenu>
                      <DropdownMenuTrigger
                        render={
                          <Button
                            variant="ghost"
                            size="icon-xs"
                            data-testid={`specializations-row-${spec.id}-menu`}
                          />
                        }
                      >
                        <MoreHorizontal className="h-4 w-4" />
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end">
                        <DropdownMenuItem
                          onClick={() => openManageGrades(spec)}
                          data-testid={`specializations-row-${spec.id}-btn-manage-grades`}
                        >
                          <Layers className="mr-2 h-4 w-4" />
                          Manage grades
                        </DropdownMenuItem>
                        <DropdownMenuItem
                          variant="destructive"
                          onClick={() => setDeleting(spec)}
                          data-testid={`specializations-row-${spec.id}-btn-delete`}
                        >
                          <Trash2 className="mr-2 h-4 w-4" />
                          Delete
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </TableCell>
                )}
              </TableRow>
              );
            })}
            {filtered.length === 0 && (
              <TableRow>
                <TableCell
                  colSpan={canManage ? 5 : 4}
                  className="py-8 text-center text-muted-foreground"
                >
                  {search
                    ? "No specializations match your search."
                    : "No specializations yet. Add them in Settings → Dictionaries → Specializations."}
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      )}

      <ConfirmDialog
        open={deleting !== null}
        onOpenChange={(open) => {
          if (!open) setDeleting(null);
        }}
        title="Delete specialization"
        description={
          deleting
            ? deleteHasReferences
              ? `"${deleting.title}" is still referenced. Detach the items below before deleting.`
              : `Delete "${deleting.title}"? This cannot be undone.`
            : ""
        }
        onConfirm={confirmDelete}
        loading={deleteBusy}
        confirmDisabled={deleteHasReferences}
      >
        <UsageReferencesList usage={deleteUsage} />
      </ConfirmDialog>

      {managingGrades && managingGradesMeta !== null ? (
        <AddGradesModal
          open
          specId={managingGrades.id}
          alreadyAdded={managingGradesMeta}
          onClose={closeManageGrades}
          onAdded={(grades) => {
            // Reflect the new grade count in the table immediately so the
            // operator sees their change without a hard reload.
            setItems((prev) =>
              prev.map((s) =>
                s.id === managingGrades.id
                  ? { ...s, grade_count: grades.length }
                  : s,
              ),
            );
            closeManageGrades();
          }}
        />
      ) : null}
    </div>
  );
}
