"""Primitive catalog v1.1 — GENERATED by scripts/gen_primitive_seed.py.

Do not edit by hand: change ``docs/plans/process-library/_catalog.yaml`` (or
the translations in the generator) and rerun the script. The YAML is not in
the public tree, so this list is what the seed migration and the runtime
read.

``kind`` is stored as data on purpose — coverage rules key on it and must
survive a code rename. ``ai_verdict`` / ``ai_as_of`` / ``ai_basis`` are a
snapshot (decision 2026-08-28): a quarterly revision rewrites them without
bumping the catalog version.
"""

from __future__ import annotations

from datetime import date
from typing import Any

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import Insert, insert

CATALOG_VERSION = "v1.1"

SEED_COLUMNS = (
    "code",
    "kind",
    "ai_verdict",
    "title_en",
    "scope_en",
    "i18n_key",
    "sort_index",
    "introduced_in",
    "ai_as_of",
    "ai_basis",
)

PRIMITIVES: list[dict[str, Any]] = [
    {
        "code": "P1",
        "kind": "cognitive",
        "ai_verdict": "strong",
        "title_en": "Extracting structure from an unstructured source",
        "scope_en": "Text, speech, a scan, or a form turned into fields and relations",
        "i18n_key": "p1",
        "sort_index": 0,
        "introduced_in": "v1",
        "ai_as_of": date(2026, 8, 26),
        "ai_basis": "frontier-2026-08",
    },
    {
        "code": "P2",
        "kind": "cognitive",
        "ai_verdict": "better_than_human",
        "title_en": "Checking against a reference and finding discrepancies",
        "scope_en": "The reference is set in advance: a playbook, a regulation, a register, a previous period",
        "i18n_key": "p2",
        "sort_index": 1,
        "introduced_in": "v1",
        "ai_as_of": date(2026, 8, 26),
        "ai_basis": "frontier-2026-08",
    },
    {
        "code": "P3",
        "kind": "cognitive",
        "ai_verdict": "strong",
        "title_en": "Rule-based classification and routing",
        "scope_en": "The rules are known and expressible; the choice is from a finite set",
        "i18n_key": "p3",
        "sort_index": 2,
        "introduced_in": "v1",
        "ai_as_of": date(2026, 8, 26),
        "ai_basis": "frontier-2026-08",
    },
    {
        "code": "P4",
        "kind": "cognitive",
        "ai_verdict": "draft",
        "title_en": "Investigating a cause across heterogeneous sources",
        "scope_en": "There is no reference; the hypothesis is built from logs, statements, and documents",
        "i18n_key": "p4",
        "sort_index": 3,
        "introduced_in": "v1",
        "ai_as_of": date(2026, 8, 26),
        "ai_basis": "frontier-2026-08",
    },
    {
        "code": "P5",
        "kind": "cognitive",
        "ai_verdict": "draft",
        "title_en": "Generating text in a given register",
        "scope_en": "A letter, a status update, a report, the wording of a correction",
        "i18n_key": "p5",
        "sort_index": 4,
        "introduced_in": "v1",
        "ai_as_of": date(2026, 8, 26),
        "ai_basis": "frontier-2026-08",
    },
    {
        "code": "P6",
        "kind": "cognitive",
        "ai_verdict": "no",
        "title_en": "Judging risk or priority in a business context",
        "scope_en": "The cost of a mistake is known only inside the company's context",
        "i18n_key": "p6",
        "sort_index": 5,
        "introduced_in": "v1",
        "ai_as_of": date(2026, 8, 26),
        "ai_basis": "frontier-2026-08",
    },
    {
        "code": "P7",
        "kind": "cognitive",
        "ai_verdict": "no",
        "title_en": "Open-ended dialogue with an external party",
        "scope_en": "Negotiation, an interview, bargaining; the set of outcomes is unknown before the conversation starts and the counterpart's reaction changes the result",
        "i18n_key": "p7",
        "sort_index": 6,
        "introduced_in": "v1",
        "ai_as_of": date(2026, 8, 31),
        "ai_basis": "frontier-2026-08",
    },
    {
        "code": "P8",
        "kind": "cognitive",
        "ai_verdict": "no",
        "title_en": "Consolidating people's contributions and resolving priority conflicts",
        "scope_en": "Assign a person, reconcile opinions, push a decision through, agree on a priority, hand over to the owner",
        "i18n_key": "p8",
        "sort_index": 7,
        "introduced_in": "v1",
        "ai_as_of": date(2026, 8, 31),
        "ai_basis": "frontier-2026-08",
    },
    {
        "code": "P9",
        "kind": "cognitive",
        "ai_verdict": "draft",
        "title_en": "Producing a working artifact from a specification",
        "scope_en": "A drawing, code, a schema, a patent claim, a training course; verified by whether it works, not by the register of its prose",
        "i18n_key": "p9",
        "sort_index": 8,
        "introduced_in": "v1",
        "ai_as_of": date(2026, 8, 26),
        "ai_basis": "frontier-2026-08",
    },
    {
        "code": "P10",
        "kind": "cognitive",
        "ai_verdict": "draft",
        "title_en": "Designing a measurement and an experiment",
        "scope_en": "What counts as the metric, how to define it operationally, how to set up a pilot so the effect is distinguishable from noise",
        "i18n_key": "p10",
        "sort_index": 9,
        "introduced_in": "v1",
        "ai_as_of": date(2026, 8, 26),
        "ai_basis": "frontier-2026-08",
    },
    {
        "code": "P11",
        "kind": "cognitive",
        "ai_verdict": "strong",
        "title_en": "Coordination by calendar, triggers, and lists",
        "scope_en": "Notify, collect responses, track readiness, put on the schedule, escalate by rule",
        "i18n_key": "p11",
        "sort_index": 10,
        "introduced_in": "v1.1",
        "ai_as_of": date(2026, 8, 31),
        "ai_basis": "frontier-2026-08",
    },
    {
        "code": "P12",
        "kind": "cognitive",
        "ai_verdict": "strong",
        "title_en": "Scripted or regulated dialogue with an external party",
        "scope_en": "The counterpart's reaction picks a branch; the set of outcomes is known before the conversation starts: a question tree, a questionnaire, a closing procedure",
        "i18n_key": "p12",
        "sort_index": 11,
        "introduced_in": "v1.1",
        "ai_as_of": date(2026, 8, 31),
        "ai_basis": "frontier-2026-08",
    },
    {
        "code": "P13",
        "kind": "cognitive",
        "ai_verdict": "draft",
        "title_en": "Producing a result accepted by a stakeholder's taste and consent",
        "scope_en": "A creative concept, a visual identity, a design direction; the acceptance criterion cannot be stated before the showing and is revealed only through the accepting party's reaction",
        "i18n_key": "p13",
        "sort_index": 12,
        "introduced_in": "v1.1",
        "ai_as_of": date(2026, 8, 31),
        "ai_basis": "frontier-2026-08",
    },
    {
        "code": "B1",
        "kind": "boundary",
        "ai_verdict": "no",
        "title_en": "Instrumental reading of a value from an object",
        "scope_en": "Temperature at a critical control point, a scan at goods receipt, weight, vital signs",
        "i18n_key": "b1",
        "sort_index": 13,
        "introduced_in": "v1",
        "ai_as_of": date(2026, 8, 26),
        "ai_basis": "frontier-2026-08",
    },
    {
        "code": "B2",
        "kind": "boundary",
        "ai_verdict": "no",
        "title_en": "Physical action on an object",
        "scope_en": "Unloading, placement, repair, withdrawing a batch, fixing defects",
        "i18n_key": "b2",
        "sort_index": 14,
        "introduced_in": "v1",
        "ai_as_of": date(2026, 8, 26),
        "ai_basis": "frontier-2026-08",
    },
    {
        "code": "B3",
        "kind": "boundary",
        "ai_verdict": "no",
        "title_en": "On-site sensory assessment of the condition of an object or a person",
        "scope_en": "A dented package, play and noise in an assembly, a patient's appearance, a user's behaviour in a task",
        "i18n_key": "b3",
        "sort_index": 15,
        "introduced_in": "v1",
        "ai_as_of": date(2026, 8, 26),
        "ai_basis": "frontier-2026-08",
    },
    {
        "code": "B4",
        "kind": "boundary",
        "ai_verdict": "no",
        "title_en": "Transferring a skill to a person with in-the-moment correction",
        "scope_en": "Demonstration, a supervised attempt, correction before the mistake sets in",
        "i18n_key": "b4",
        "sort_index": 16,
        "introduced_in": "v1",
        "ai_as_of": date(2026, 8, 26),
        "ai_basis": "frontier-2026-08",
    },
]


def seed_insert() -> Insert:
    """``INSERT ... ON CONFLICT DO NOTHING`` for the whole catalog.

    Untargeted on purpose: ``primitives`` is unique on ``code`` *and* on
    ``i18n_key``, so a target of ``code`` alone would let a re-seed abort on
    the i18n key of a row whose code was rewritten between catalog versions.

    Shared by migration ``v2prim01`` and the unit tests, so what the tests
    prove about idempotency is exactly what production runs. Built on a
    lightweight ``sa.table`` rather than the ORM model so the migration
    stays decoupled from later model changes.
    """
    table = sa.table("primitives", *(sa.column(name) for name in SEED_COLUMNS))
    return insert(table).values(PRIMITIVES).on_conflict_do_nothing()
