"""I3: add email_logs table for delivery tracking

Revision ID: 00f8552f63fd
Revises: b3c4d5e6f7a8
Create Date: 2026-04-20 10:15:32.917484
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00f8552f63fd"
down_revision: str | None = "b3c4d5e6f7a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_logs",
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("recipient", sa.String(length=320), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("template_code", sa.String(length=100), nullable=True),
        sa.Column(
            "status", sa.String(length=50), server_default="sent", nullable=False
        ),
        sa.Column("message_id", sa.String(length=200), nullable=True),
        sa.Column("error", sa.String(length=2000), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="1", nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_logs_message_id"), "email_logs", ["message_id"], unique=False
    )
    op.create_index(
        op.f("ix_email_logs_recipient"), "email_logs", ["recipient"], unique=False
    )
    op.create_index(
        op.f("ix_email_logs_tenant_id"), "email_logs", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_logs_tenant_id"), table_name="email_logs")
    op.drop_index(op.f("ix_email_logs_recipient"), table_name="email_logs")
    op.drop_index(op.f("ix_email_logs_message_id"), table_name="email_logs")
    op.drop_table("email_logs")
    # ### end Alembic commands ###
