"""phase2_dictionary_competence_grade_system

Revision ID: 73e0bafc0692
Revises: abe66531e6e4
Create Date: 2026-04-15 15:04:51.427068
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "73e0bafc0692"
down_revision: str | None = "abe66531e6e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skill_levels",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("sort_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "competence_groups",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("sort_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["competence_groups.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_competence_groups_parent_id"),
        "competence_groups",
        ["parent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_competence_groups_tenant_id"),
        "competence_groups",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "dictionary_items",
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("sort_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "type", "title", "tenant_id", name="uq_dict_item_type_title_tenant"
        ),
    )
    op.create_index(
        op.f("ix_dictionary_items_tenant_id"),
        "dictionary_items",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dictionary_items_type"), "dictionary_items", ["type"], unique=False
    )
    op.create_table(
        "competences",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("competence_type_id", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competence_type_id"], ["dictionary_items.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["competence_groups.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_competences_group_id"), "competences", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_competences_tenant_id"), "competences", ["tenant_id"], unique=False
    )
    op.create_table(
        "grade_specializations",
        sa.Column("grade_id", sa.UUID(), nullable=False),
        sa.Column("specialization_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=600), nullable=True),
        sa.Column("sort_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grade_id"], ["dictionary_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["specialization_id"], ["dictionary_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "grade_id", "specialization_id", name="uq_grade_spec_tenant"
        ),
    )
    op.create_index(
        op.f("ix_grade_specializations_tenant_id"),
        "grade_specializations",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "grade_competence_links",
        sa.Column("grade_specialization_id", sa.UUID(), nullable=False),
        sa.Column("competence_id", sa.UUID(), nullable=False),
        sa.Column("skill_level_id", sa.UUID(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competence_id"], ["competences.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["grade_specialization_id"],
            ["grade_specializations.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_level_id"], ["skill_levels.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_grade_competence_links_grade_specialization_id"),
        "grade_competence_links",
        ["grade_specialization_id"],
        unique=False,
    )
    op.create_table(
        "indicators",
        sa.Column("title", sa.String(length=600), nullable=False),
        sa.Column("weight", sa.Integer(), server_default="0", nullable=False),
        sa.Column("sort_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column("skill_level_id", sa.UUID(), nullable=False),
        sa.Column("competence_id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competence_id"], ["competences.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["skill_level_id"], ["skill_levels.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_indicators_competence_id"),
        "indicators",
        ["competence_id"],
        unique=False,
    )
    op.create_table(
        "materials",
        sa.Column("title", sa.String(length=600), nullable=False),
        sa.Column("format", sa.String(length=100), nullable=True),
        sa.Column("link", sa.String(length=600), nullable=True),
        sa.Column("study_time", sa.Integer(), nullable=True),
        sa.Column("sort_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column("skill_level_id", sa.UUID(), nullable=False),
        sa.Column("competence_id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competence_id"], ["competences.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["skill_level_id"], ["skill_levels.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_materials_competence_id"), "materials", ["competence_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_materials_competence_id"), table_name="materials")
    op.drop_table("materials")
    op.drop_index(op.f("ix_indicators_competence_id"), table_name="indicators")
    op.drop_table("indicators")
    op.drop_index(
        op.f("ix_grade_competence_links_grade_specialization_id"),
        table_name="grade_competence_links",
    )
    op.drop_table("grade_competence_links")
    op.drop_index(
        op.f("ix_grade_specializations_tenant_id"), table_name="grade_specializations"
    )
    op.drop_table("grade_specializations")
    op.drop_index(op.f("ix_competences_tenant_id"), table_name="competences")
    op.drop_index(op.f("ix_competences_group_id"), table_name="competences")
    op.drop_table("competences")
    op.drop_index(op.f("ix_dictionary_items_type"), table_name="dictionary_items")
    op.drop_index(op.f("ix_dictionary_items_tenant_id"), table_name="dictionary_items")
    op.drop_table("dictionary_items")
    op.drop_index(
        op.f("ix_competence_groups_tenant_id"), table_name="competence_groups"
    )
    op.drop_index(
        op.f("ix_competence_groups_parent_id"), table_name="competence_groups"
    )
    op.drop_table("competence_groups")
    op.drop_table("skill_levels")
    # ### end Alembic commands ###
