"""phase3_assessment_exam_notification

Revision ID: fc2bda23a969
Revises: aca1005a8e45
Create Date: 2026-04-15 18:48:55.259291
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fc2bda23a969"
down_revision: str | None = "aca1005a8e45"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessment_statuses",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "assessment_types",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "notification_templates",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("subject_template", sa.String(length=500), nullable=False),
        sa.Column("body_template", sa.String(length=5000), nullable=False),
        sa.Column(
            "notification_type",
            sa.String(length=50),
            server_default="email",
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "answer_scales",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_answer_scales_tenant_id"), "answer_scales", ["tenant_id"], unique=False
    )
    op.create_table(
        "answer_options",
        sa.Column("scale_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("weight", sa.Integer(), server_default="0", nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("sort_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["scale_id"], ["answer_scales.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_answer_options_scale_id"), "answer_options", ["scale_id"], unique=False
    )
    op.create_table(
        "cpas",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("type_id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.String(length=50), server_default="draft", nullable=False
        ),
        sa.Column("scale_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scale_id"],
            ["answer_scales.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["assessment_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cpas_tenant_id"), "cpas", ["tenant_id"], unique=False)
    op.create_table(
        "mass_exams",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("initiator_id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.String(length=50), server_default="draft", nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["initiator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mass_exams_tenant_id"), "mass_exams", ["tenant_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("recipient_id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.String(length=50), server_default="pending", nullable=False
        ),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["notification_templates.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_recipient_id"),
        "notifications",
        ["recipient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_tenant_id"), "notifications", ["tenant_id"], unique=False
    )
    op.create_table(
        "assessments",
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("type_id", sa.UUID(), nullable=False),
        sa.Column("status_id", sa.UUID(), nullable=False),
        sa.Column("specialization_id", sa.UUID(), nullable=True),
        sa.Column("grade_id", sa.UUID(), nullable=True),
        sa.Column("scale_id", sa.UUID(), nullable=True),
        sa.Column("initiator_id", sa.UUID(), nullable=False),
        sa.Column("approver_id", sa.UUID(), nullable=True),
        sa.Column("cpa_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approver_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["cpa_id"], ["cpas.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["grade_id"],
            ["dictionary_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["initiator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scale_id"],
            ["answer_scales.id"],
        ),
        sa.ForeignKeyConstraint(
            ["specialization_id"],
            ["dictionary_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["assessment_statuses.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["assessment_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessments_cpa_id"), "assessments", ["cpa_id"], unique=False
    )
    op.create_index(
        op.f("ix_assessments_employee_id"), "assessments", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_assessments_tenant_id"), "assessments", ["tenant_id"], unique=False
    )
    op.create_table(
        "exam_pass_marks",
        sa.Column("mass_exam_id", sa.UUID(), nullable=False),
        sa.Column("grade_id", sa.UUID(), nullable=True),
        sa.Column("specialization_id", sa.UUID(), nullable=True),
        sa.Column("min_score_percent", sa.Integer(), nullable=True),
        sa.Column("min_score_points", sa.Integer(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grade_id"],
            ["dictionary_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mass_exam_id"], ["mass_exams.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["specialization_id"],
            ["dictionary_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exam_pass_marks_mass_exam_id"),
        "exam_pass_marks",
        ["mass_exam_id"],
        unique=False,
    )
    op.create_table(
        "exam_questions",
        sa.Column("mass_exam_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("question_type", sa.String(length=50), nullable=False),
        sa.Column("sort_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column("weight", sa.Integer(), server_default="1", nullable=False),
        sa.Column("image_url", sa.String(length=600), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mass_exam_id"], ["mass_exams.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exam_questions_mass_exam_id"),
        "exam_questions",
        ["mass_exam_id"],
        unique=False,
    )
    op.create_table(
        "exams",
        sa.Column("mass_exam_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.String(length=50), server_default="assigned", nullable=False
        ),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("max_score", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["mass_exam_id"], ["mass_exams.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exams_employee_id"), "exams", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_exams_mass_exam_id"), "exams", ["mass_exam_id"], unique=False
    )
    op.create_index(op.f("ix_exams_tenant_id"), "exams", ["tenant_id"], unique=False)
    op.create_table(
        "assessment_competences",
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("competence_id", sa.UUID(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["assessments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["competence_id"], ["competences.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessment_competences_assessment_id"),
        "assessment_competences",
        ["assessment_id"],
        unique=False,
    )
    op.create_table(
        "assessment_participants",
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("is_completed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["assessments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessment_participants_assessment_id"),
        "assessment_participants",
        ["assessment_id"],
        unique=False,
    )
    op.create_table(
        "assessment_results",
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("competence_id", sa.UUID(), nullable=False),
        sa.Column("avg_score", sa.Float(), nullable=False),
        sa.Column("calibrated_score", sa.Float(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["assessments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["competence_id"],
            ["competences.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessment_results_assessment_id"),
        "assessment_results",
        ["assessment_id"],
        unique=False,
    )
    op.create_table(
        "exam_answers",
        sa.Column("exam_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column(
            "selected_option_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("text_answer", sa.String(length=5000), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("score", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["exam_id"], ["exams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["exam_questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exam_answers_exam_id"), "exam_answers", ["exam_id"], unique=False
    )
    op.create_table(
        "pdps",
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("assessment_id", sa.UUID(), nullable=True),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=True),
        sa.Column(
            "status", sa.String(length=50), server_default="draft", nullable=False
        ),
        sa.Column("specialization_id", sa.UUID(), nullable=True),
        sa.Column("grade_id", sa.UUID(), nullable=True),
        sa.Column("total_progress", sa.Integer(), server_default="0", nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["assessments.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["grade_id"],
            ["dictionary_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["specialization_id"],
            ["dictionary_items.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pdps_employee_id"), "pdps", ["employee_id"], unique=False)
    op.create_index(op.f("ix_pdps_tenant_id"), "pdps", ["tenant_id"], unique=False)
    op.create_table(
        "question_options",
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("sort_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_correct", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["exam_questions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_options_question_id"),
        "question_options",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "assessment_answers",
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("participant_id", sa.UUID(), nullable=False),
        sa.Column("indicator_id", sa.UUID(), nullable=False),
        sa.Column("answer_option_id", sa.UUID(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("comment", sa.String(length=1000), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["answer_option_id"],
            ["answer_options.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["assessments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["indicator_id"],
            ["indicators.id"],
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"], ["assessment_participants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessment_answers_assessment_id"),
        "assessment_answers",
        ["assessment_id"],
        unique=False,
    )
    op.create_table(
        "pdp_items",
        sa.Column("pdp_id", sa.UUID(), nullable=False),
        sa.Column("competence_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("sort_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_passed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "entity_type", sa.String(length=20), server_default="custom", nullable=False
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competence_id"], ["competences.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["pdp_id"], ["pdps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pdp_items_pdp_id"), "pdp_items", ["pdp_id"], unique=False)
    op.create_table(
        "pdp_comments",
        sa.Column("pdp_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.String(length=2000), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["item_id"], ["pdp_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pdp_id"], ["pdps.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pdp_comments_pdp_id"), "pdp_comments", ["pdp_id"], unique=False
    )
    op.create_table(
        "pdp_item_materials",
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=600), nullable=False),
        sa.Column("format", sa.String(length=100), nullable=True),
        sa.Column("link", sa.String(length=600), nullable=True),
        sa.Column("study_time", sa.Integer(), nullable=True),
        sa.Column("sort_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_passed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["item_id"], ["pdp_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["material_id"], ["materials.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pdp_item_materials_item_id"),
        "pdp_item_materials",
        ["item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_pdp_item_materials_item_id"), table_name="pdp_item_materials"
    )
    op.drop_table("pdp_item_materials")
    op.drop_index(op.f("ix_pdp_comments_pdp_id"), table_name="pdp_comments")
    op.drop_table("pdp_comments")
    op.drop_index(op.f("ix_pdp_items_pdp_id"), table_name="pdp_items")
    op.drop_table("pdp_items")
    op.drop_index(
        op.f("ix_assessment_answers_assessment_id"), table_name="assessment_answers"
    )
    op.drop_table("assessment_answers")
    op.drop_index(
        op.f("ix_question_options_question_id"), table_name="question_options"
    )
    op.drop_table("question_options")
    op.drop_index(op.f("ix_pdps_tenant_id"), table_name="pdps")
    op.drop_index(op.f("ix_pdps_employee_id"), table_name="pdps")
    op.drop_table("pdps")
    op.drop_index(op.f("ix_exam_answers_exam_id"), table_name="exam_answers")
    op.drop_table("exam_answers")
    op.drop_index(
        op.f("ix_assessment_results_assessment_id"), table_name="assessment_results"
    )
    op.drop_table("assessment_results")
    op.drop_index(
        op.f("ix_assessment_participants_assessment_id"),
        table_name="assessment_participants",
    )
    op.drop_table("assessment_participants")
    op.drop_index(
        op.f("ix_assessment_competences_assessment_id"),
        table_name="assessment_competences",
    )
    op.drop_table("assessment_competences")
    op.drop_index(op.f("ix_exams_tenant_id"), table_name="exams")
    op.drop_index(op.f("ix_exams_mass_exam_id"), table_name="exams")
    op.drop_index(op.f("ix_exams_employee_id"), table_name="exams")
    op.drop_table("exams")
    op.drop_index(op.f("ix_exam_questions_mass_exam_id"), table_name="exam_questions")
    op.drop_table("exam_questions")
    op.drop_index(op.f("ix_exam_pass_marks_mass_exam_id"), table_name="exam_pass_marks")
    op.drop_table("exam_pass_marks")
    op.drop_index(op.f("ix_assessments_tenant_id"), table_name="assessments")
    op.drop_index(op.f("ix_assessments_employee_id"), table_name="assessments")
    op.drop_index(op.f("ix_assessments_cpa_id"), table_name="assessments")
    op.drop_table("assessments")
    op.drop_index(op.f("ix_notifications_tenant_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_recipient_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_mass_exams_tenant_id"), table_name="mass_exams")
    op.drop_table("mass_exams")
    op.drop_index(op.f("ix_cpas_tenant_id"), table_name="cpas")
    op.drop_table("cpas")
    op.drop_index(op.f("ix_answer_options_scale_id"), table_name="answer_options")
    op.drop_table("answer_options")
    op.drop_index(op.f("ix_answer_scales_tenant_id"), table_name="answer_scales")
    op.drop_table("answer_scales")
    op.drop_table("notification_templates")
    op.drop_table("assessment_types")
    op.drop_table("assessment_statuses")
    # ### end Alembic commands ###
