"""phase4_talent_market_storage

Revision ID: fc66707e4d5b
Revises: c3fc300775f8
Create Date: 2026-04-15 20:47:49.853146
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc66707e4d5b"
down_revision: str | None = "c3fc300775f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("path", sa.String(length=600), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_files_tenant_id"), "files", ["tenant_id"], unique=False)
    op.create_table(
        "talent_cards",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("card_type", sa.String(length=50), nullable=False),
        sa.Column(
            "status", sa.String(length=50), server_default="draft", nullable=False
        ),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("division_id", sa.UUID(), nullable=True),
        sa.Column("is_published", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["division_id"], ["divisions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_talent_cards_tenant_id"), "talent_cards", ["tenant_id"], unique=False
    )
    op.create_table(
        "talent_card_competences",
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("competence_id", sa.UUID(), nullable=False),
        sa.Column("skill_level_id", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["card_id"], ["talent_cards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["competence_id"],
            ["competences.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_level_id"],
            ["skill_levels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_talent_card_competences_card_id"),
        "talent_card_competences",
        ["card_id"],
        unique=False,
    )
    op.create_table(
        "talent_card_requirements",
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("min_experience_years", sa.Integer(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["card_id"], ["talent_cards.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_talent_card_requirements_card_id"),
        "talent_card_requirements",
        ["card_id"],
        unique=False,
    )
    op.create_table(
        "talent_card_specializations",
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("specialization_id", sa.UUID(), nullable=False),
        sa.Column("grade_id", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["card_id"], ["talent_cards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["grade_id"],
            ["dictionary_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["specialization_id"],
            ["dictionary_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_talent_card_specializations_card_id"),
        "talent_card_specializations",
        ["card_id"],
        unique=False,
    )
    op.create_table(
        "talent_candidates",
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.String(length=50), server_default="nominated", nullable=False
        ),
        sa.Column("match_score", sa.Integer(), nullable=True),
        sa.Column("assessment_id", sa.UUID(), nullable=True),
        sa.Column("pdp_id", sa.UUID(), nullable=True),
        sa.Column("response_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("appointed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["assessments.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["card_id"], ["talent_cards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(["pdp_id"], ["pdps.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_talent_candidates_card_id"),
        "talent_candidates",
        ["card_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_talent_candidates_card_id"), table_name="talent_candidates")
    op.drop_table("talent_candidates")
    op.drop_index(
        op.f("ix_talent_card_specializations_card_id"),
        table_name="talent_card_specializations",
    )
    op.drop_table("talent_card_specializations")
    op.drop_index(
        op.f("ix_talent_card_requirements_card_id"),
        table_name="talent_card_requirements",
    )
    op.drop_table("talent_card_requirements")
    op.drop_index(
        op.f("ix_talent_card_competences_card_id"), table_name="talent_card_competences"
    )
    op.drop_table("talent_card_competences")
    op.drop_index(op.f("ix_talent_cards_tenant_id"), table_name="talent_cards")
    op.drop_table("talent_cards")
    op.drop_index(op.f("ix_files_tenant_id"), table_name="files")
    op.drop_table("files")
    # ### end Alembic commands ###
